<?php
/**
 * This is the default template part for the
 * checkout element in the content-quick-view-added template
 * part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-quick-view-added/elements/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_quick_view_added_before_item_count_element' ); ?>
<div class="it-exchange-quick-view-cart-item-count">
	<?php echo sprintf( translate_nooped_plural( _n_noop( 'Currently %s item in your cart.', 'Currently %s items in your cart.' ), it_exchange( 'cart.get-item-count' ) ), it_exchange( 'cart.get-item-count' ) ); ?>
</div>
<?php do_action( 'it_exchange_content_quick_view_added_after_item_count_element' ); ?>