<?php
/**
 * This is the default template for the Subtotal
 * detail in the totals loop of the content-quick-view-added
 * template part.
 *
 * @since 1.4.0
 * @version 1.0.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_confirmation_before_totals_subtotal_element' ); ?>
<div class="it-exchange-quick-view-totals it-exchange-quick-view-subtotal">
	<p><?php _e( 'Subotal:', 'LION' ); ?><span><?php it_exchange( 'cart', 'subtotal' ); ?></span></p>
</div>
<?php do_action( 'it_exchange_content_confirmation_after_totals_subtotal_element' ); ?>
