<?php
/**
 * This is the default template for the Total
 * element in the totals loop of the content-quick-view-added
 * template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-quick-view-added/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_quick_view_added_before_totals_total_element' ); ?>
<div class="it-exchange-quick-view-totals it-exchange-quick-view-total">
	<p><?php _e( 'Total', 'LION' ); ?><span><?php it_exchange( 'cart', 'total' ); ?></span></p>
</div>
<?php do_action( 'it_exchange_content_quick_view_added_after_totals_total_element' ); ?>
