<?php
/**
 * Default template for displaying the quick view
 * on the product page.
 * 
 * @since 1.0.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange_Addon_Quick_View
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/ directory located
 * in your theme.
*/
?>

<?php do_action( 'it_exchange_content_store_before_quick_view_element' ); ?>
	<?php it_exchange( 'quick-view', 'button' ); ?>
<?php do_action( 'it_exchange_content_store_after_quick_view_element' ); ?>