<?php
/**
 * The default template part for the product
 * description in the content-quick-view template
 * part's product-info loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange/content-quick-view/elements
 * directory located in your theme.
*/
?>

<?php if ( it_exchange( 'product', 'has-description' ) ) : ?>
	<?php do_action( 'it_exchange_quick_view_before_description_element' ); ?>
	<div class="it-exchange-product-description">
		<?php it_exchange( 'product', 'description', array( 'max-length' => 400 ) ); ?>
	</div>
	<?php do_action( 'it_exchange_quick_view_after_description_element' ); ?>
<?php endif; ?>