<?php
/**
 * The default template part for the product
 * super widget in the content-quick-view template
 * part's product-info loop.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange/content-quick-view/elements
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_quick_view_before_super_widget_element' ); ?>
<div class="it-exchange-quick-view-purchase-options">
	<?php it_exchange( 'product', 'purchase-options', array( 'buy-now-edit-quantity' => false, 'add-to-cart-edit-quantity' => false ) ); ?>
</div>
<?php do_action( 'it_exchange_quick_view_after_super_widget_element' ); ?>