<?php
/**
 * The default product-info loop for the
 * content-quick-view-added.php template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange/content-quick-view-added/loops
 * directory located in your theme.
*/
?>

<?php do_action( 'it_exchange_quick_view_added_before_product_info_loop' ); ?>
<?php foreach ( it_exchange_get_template_part_elements( 'content_quick_view_added', 'product_info_loop', array( 'thumbnail', 'title', 'base-price' ) ) as $detail ) : ?>
	<?php it_exchange_get_template_part( 'content-quick-view-added/elements/' . $detail ); ?>
<?php endforeach; ?>
<?php do_action( 'it_exchange_quick_view_added_after_product_info_loop' ); ?>