<?php
/**
 * Default template for displaying the a single
 * exchange product.
 *
 * @since 0.4.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
*/
?>

<?php do_action( 'it_exchange_quick_view_added_before_wrap' ); ?>
<div id="it-exchange-quick-view-added" class="<?php echo ( ! it_exchange( 'product', 'has-images' ) ) ? ' it-exchange-product-no-images' : 'it-exchange-product-has-images'; ?>">
	<div class="it-exchange-product-info-title it-exchange-product-added-title">
		<div class="it-exchange-inner">
			<?php _e( 'Product Added to Cart', 'LION' ); ?>
		</div>
	</div>
	<div class="it-exchange-product-info">
		<div class="it-exchange-inner">
			<?php it_exchange_get_template_part( 'content-quick-view-added/loops/product-info' ); ?>
		</div>
	</div>
	<div class="it-exchange-cart-summary">
		<div class="it-exchange-inner it-exchange-clearfix">
			<?php it_exchange_get_template_part( 'content-quick-view-added/loops/cart-summary' ); ?>
		</div>
	</div>
</div>
<?php do_action( 'it_exchange_quick_view_added_after_wrap' ); ?>
